version: '2.1'
services:

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN}
      - PGADMIN_DEFAULT_PASSWORD=${PGPASSWORD}
    ports:
      - "16543:80"
    depends_on:
      - db

  pgtap:
    image: hbpmip/pgtap
    environment:
      - DATABASE=${DATABASE}
      - USER=${USERNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - ./pgtap:/test
    depends_on:
      - pgadmin

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/${DATABASE} -schemas=public -user=${USERNAME} -password=${PASSWORD} migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASE}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2