CREATE TABLE directors (  
    directorsId INT GENERATED BY DEFAULT AS IDENTITY,  
    directorsName VARCHAR(50) NOT NULL,  
    PRIMARY KEY (directorsId)
);  



CREATE TABLE movies(  
    moviesId INT GENERATED BY DEFAULT AS IDENTITY,  
    moviesName  VARCHAR(50) NOT NULL,  
    directorsId INT NOT NULL,  
    releaseYear SMALLINT NOT NULL,  
    PRIMARY KEY (moviesId),
    FOREIGN KEY(directorsId) REFERENCES directors (directorsId)
);   
  
 
