CREATE TABLE directors (  
    directorsId INT GENERATED BY DEFAULT AS IDENTITY,  
    directorsName VARCHAR(50) NOT NULL,  
    PRIMARY KEY directorsId
);  
  
CREATE TABLE movies(  
    moviesId INT GENERATED BY DEFAULT AS IDENTITY,  
    moviesName  VARCHAR(50) NOT NULL,  
    directorId INT NOT NULL,  
    releaseYear SMALLINT NOT NULL,  
    PRIMARY KEY moviesId,
    FOREIGN KEY(directorId) REFERENCES directors (directorsId)
);  
  
 
